### Get all events
GET http://localhost:5000/api/events

### Get Event by ID
GET http://localhost:5000/api/events/fc11


### Post new event
POST http://localhost:5000/api/events
Content-Type: application/json

{
  "banner": "DHS2025/dhs2025-se-banner.webp",
  "title": "DreamHack Stockholm 2025",
  "games": "Melee",
  "description": "Smash Bros. Melee is back at another DreamhHack event, this time part of the <a target=\"_blank\" href=\"https://dreamhack.com/stockholm/#/\">Stockholm edition</a>. There singles and doubles competitions. Max capacity is currently unknown. Entree to the tournaments are free but a ticket to the festival must be purchased on the dreamhack event's website.",
  "dates": [
    "2025-11-28T00:00:00.000Z",
    "2025-11-30T20:00:00.000Z"
  ],
  "location": {
    "municipality": "Stockholm",
    "country": "Sweden"
  },
  "details": "https://www.start.gg/tournament/ssbm-sf6-dreamhack-stockholm-2025/",
  "slug": "dhs-2025"
}

