### Get all events
GET http://localhost:5000/api/events

### Get Event by ID
GET http://localhost:5000/api/events/fc11


### Post new event
POST http://localhost:5000/api/events
Content-Type: application/json

{
  "banner": "Teaghlach/teaghlach-se-banner.png",
  "title": "Teaghlach",
  "games": "Melee",
  "description": "The TO team that brought you the Schism series are delighted to launch a brand new 4-day Melee experience! Coming a mere 3 years later than initially promised, Teaghlach (\"family\" as Gaeilge) is a self-catered, community-driven retreat packed with Melee and mischief. They're bringing together the very best of Irish Melee along with international talent to one of Ireland's most beautiful settings. Expect intense sets, late-night sessions and a whole lot of craic.",
  "dates": [
    "2025-10-27T00:00:00.000Z",
    "2025-12-28T20:00:00.000Z"
  ],
  "location": {
    "municipality": "Wicklow",
    "country": "Ireland"
  },
  "details": "https://www.start.gg/tournament/teaghlach",
  "slug": "teaghlach"
}

