### Get all events
GET http://localhost:5001/api/events

### Get Event by ID
GET http://localhost:5001/api/events/fc11


### Post new event
POST http://localhost:5001/api/events
Content-Type: application/json

{
  "banner": "Lennied2/lennied-2-se-banner.webp",
  "title": "Lennied: Fatta the Lan",
  "games": "Melee",
  "description": "Hosted in London's <a target=\"_blank\" href=\"https://www.redbull.com/gb-en/projects/gaming-sphere/\">Red Bull Gaming Sphere</a>, Lennied is back for another edition with regular competitions for Melee singles & doubles and Red Bull God's and Gatekeepers style crews. There's also a mystery game to compete in.",
  "dates": [
    "2026-10-03T00:00:00.000Z",
    "2026-10-04T20:00:00.000Z"
  ],
  "location": {
    "municipality": "London",
    "country": "England"
  },
  "details": "https://www.start.gg/lennied-fatta-the-lan/",
  "slug": "lennied-2"
}

### Post new event part of circuit
POST http://localhost:5001/api/events
Content-Type: application/json

{
  "banner": "Lennied2/lennied-2-se-banner.webp",
  "title": "Lennied: Fatta the Lan",
  "games": "Melee",
  "description": "Hosted in London's <a target=\"_blank\" href=\"https://www.redbull.com/gb-en/projects/gaming-sphere/\">Red Bull Gaming Sphere</a>, Lennied is back for another edition with regular competitions for Melee singles & doubles and Red Bull God's and Gatekeepers style crews. There's also a mystery game to compete in.",
  "dates": [
    "2026-10-03T00:00:00.000Z",
    "2026-10-04T20:00:00.000Z"
  ],
  "location": {
    "municipality": "London",
    "country": "England"
  },
  "circuits": [
    {
      "slug": "cloud-chasers"
    }
  ],
  "details": "https://www.start.gg/lennied-fatta-the-lan/",
  "slug": "lennied-2"
}

